### ISSUE TITLE
Test run fails:  NameError: name 'msg' is not defined, Could not start chrome driver using the path './drivers/chromedriver*'

### ISSUE THREAD

**Issue by p00j4** [golemhq/golem#104]
Starting with the project
**Error 1** The test run fails due to chromdriver is not properly set. H
The chromedriver is in the directory ./drivers/chromedriver*'
and its set in the settings on the same path

**Error 2:** the exception block fails because the variable "msg" is undefined. For which I'm willing to raise Pull Request, does it work?

### Stacktrace
```
13:08:20.951 INFO Test execution started: image_push
13:08:20.951 INFO Browser: chrome
13:08:20.967 ERROR Could not start chrome driver using the path './drivers/chromedriver*', check the settings file.
13:08:20.971 INFO Traceback (most recent call last):
File "/Users/pooja/venv/python3/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 76, in start
stdin=PIPE)
File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 709, in __init__
restore_signals, start_new_session)
File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1344, in _execute_child
raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/Users/pooja/venv/python3/golem_fw/drivers/chromedriver_2.38'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/Users/pooja/venv/python3/lib/python3.6/site-packages/golem/browser.py", line 268, in open_browser
chrome_options=chrome_options)
File "/Users/pooja/venv/python3/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 68, in __init__
self.service.start()
File "/Users/pooja/venv/python3/lib/python3.6/site-packages/selenium/webdriver/common/service.py", line 88, in start
os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver_2.38' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home
13:08:20.973 ERROR An error ocurred:
File "/Users/pooja/venv/python3/lib/python3.6/site-packages/golem/test_runner/test_runner.py", line 122, in run_test
test_module.test(execution.data)
File "/Users/pooja/venv/python3/golem_fw/projects/flash/tests/image_push.py", line 10, in test
navigate("https://www.google.com")
File "/Users/pooja/venv/python3/lib/python3.6/site-packages/golem/actions.py", line 337, in navigate
driver = browser.get_browser()
File "/Users/pooja/venv/python3/lib/python3.6/site-packages/golem/browser.py", line 343, in get_browser
open_browser()
File "/Users/pooja/venv/python3/lib/python3.6/site-packages/golem/browser.py", line 273, in open_browser
raise Exception(msg)
NameError: name 'msg' is not defined
Result: fail 
Error: NameError: name 'msg' is not defined 
Elapsed Time: 0.02
Browser: chrome
Steps:
```

**Comment by p00j4** [comment]
Yeah, my bad, had used webdriver-manager and not sure what was wrong, thanks @lucianopuccio for pointing the right clue. Retrying with the self download. Getting into some or the other errors 
like 

### Test started running but went into infinite state a 
logs
```
127.0.0.1 - - [18/May/2018 12:41:38] "POST /check_test_case_run_result/ HTTP/1.1" 200 -
127.0.0.1 - - [18/May/2018 12:41:42] "POST /check_test_case_run_result/ HTTP/1.1" 200 -
127.0.0.1 - - [18/May/2018 12:41:46] "POST /check_test_case_run_result/ HTTP/1.1" 200 -
```
and then on stopping manually, ran into another problem that it doesn't load the app itself
logs:
 ```No such file or directory: '/Users/pooja/venv/python3/golem_fw/drivers/users.json'```

Seeing this understood that force closing has deleted the required user.json may be, hence download the [example app](https://github.com/lucianopuccio/golem-demo) and trying running its suit, which fails with:
```
golem/browser.py", line 312, in open_browser
    desired_capabilities=desired_capabilities)
TypeError: __init__() got an unexpected keyword argument 'command_executor'
```

Trying to dig into and find out whats wrong

**Comment by fizerkhan** [comment]
Me too, getting related error.

```
Exception: Could not start chrome driver using the path './drivers/chromedriver_2.38', check the settings file.
```

I do have the chrome driver 

```
$ ll drivers/chromedriver_2.38
-rwxrwxrwx 1 vagrant vagrant 7969976 May 19 06:55 drivers/chromedriver_2.38*
```

**Comment by luciano-renzi** [comment]
Stale. Reopen if this is still happening. Thanks
