### ISSUE TITLE
assert_alert_text not working when "screenshot_on_step": true in global setting

### ISSUE THREAD

**Issue by Sunil-Rathore** [golemhq/golem#221]
when "screenshot_on_step": true in global setting then assert_alert_text failing and getting below issue
19:52:29.572 INFO Test execution started: alert
19:52:29.573 INFO Browser: firefox
19:52:29.579 INFO Test started: test
19:52:29.581 INFO Navigate to: 'https://www.web-playground.net//alert'
19:52:42.890 INFO Click alert-button
19:52:43.041 ERROR UnexpectedAlertPresentException: Alert Text: None
Message: Dismissed user prompt dialog: an alert
Traceback (most recent call last):
File "d:\golem_master\golem\test_runner\test_runner.py", line 202, in run_test_function
f(execution.data)
File "D:\golem_project\projects\gole_project\tests\alert.py", line 5, in test
click(('id', 'alert-button'))
File "d:\golem_master\golem\actions.py", line 914, in click
element.click()
File "C:\Users\sunil.rathore\AppData\Local\Programs\Python\Python38-32\lib\contextlib.py", line 120, in __exit__
next(self.gen)
File "d:\golem_master\golem\actions.py", line 186, in _step
_screenshot_on_step()
File "d:\golem_master\golem\actions.py", line 175, in _screenshot_on_step
_screenshot_on_condition(execution.settings['screenshot_on_step'])
File "d:\golem_master\golem\actions.py", line 154, in _screenshot_on_condition
screenshot_filename = _capture_screenshot(screenshot_name)
File "d:\golem_master\golem\actions.py", line 97, in _capture_screenshot
get_browser().get_screenshot_as_file(screenshot_path)
File "C:\Users\sunil.rathore\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1032, in get_screenshot_as_file
png = self.get_screenshot_as_png()
File "C:\Users\sunil.rathore\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1064, in get_screenshot_as_png
return base64.b64decode(self.get_screenshot_as_base64().encode('ascii'))
File "C:\Users\sunil.rathore\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1074, in get_screenshot_as_base64
return self.execute(Command.SCREENSHOT)['value']
File "C:\Users\sunil.rathore\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
self.error_handler.check_response(response)
File "C:\Users\sunil.rathore\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 241, in check_response
raise exception_class(message, screen, stacktrace, alert_text)
selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: None
19:52:43.182 INFO Test Result: CODE ERROR

Note: if "screenshot_on_step": false in global setting then assert_alert_text  working fine.
reason: it's look like screenshot nt able take when alert present so in this case when click on alert-button so alert come immediately so it's failing.

**Comment by luciano-renzi** [comment]
Looks like Selenium can't take screenshots when there's an alert open. I added a try/except block and when a screenshot cannot be taken it will log a warning

**Comment by luciano-renzi** [comment]
good find!
