### ISSUE TITLE
Fails to create directory from gui

### ISSUE THREAD

**Issue by D3f0** [golemhq/golem#85]
I created a project called `billing` and attempted to create a directory inside of it, but web ui fails.
I can see this traceback:
```
127.0.0.1 - - [02/Jan/2018 17:34:11] "POST /new_tree_element/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/ndefosse/.virtualenvs/golem/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/ndefosse/.virtualenvs/golem/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/ndefosse/.virtualenvs/golem/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/ndefosse/.virtualenvs/golem/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/ndefosse/.virtualenvs/golem/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/ndefosse/.virtualenvs/golem/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/ndefosse/.virtualenvs/golem/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/ndefosse/.virtualenvs/golem/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/ndefosse/.virtualenvs/golem/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/ndefosse/.virtualenvs/golem/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/ndefosse/.virtualenvs/golem/lib/python3.6/site-packages/golem/gui/__init__.py", line 580, in new_tree_element
    element_name, dir_type='suites')
  File "/Users/ndefosse/.virtualenvs/golem/lib/python3.6/site-packages/golem/core/io_manager.py", line 34, in new_directory
    utils.create_new_directory(path=path, add_init=True)
```

**Comment by luciano-renzi** [comment]
Stale. Closing.
